name: "Test Package"
description: "Run tests for a package (patched and optionally unpatched versions)"
inputs:
  workdir:
    description: "Working directory containing the test environment"
    required: true
  package:
    description: "Package name to test"
    required: true
  part:
    description: "Part number of the package to test (optional)"
    required: false
  test-mode:
    description: "Test mode (stop-on-success, run-all)"
    required: true
  test-scope:
    description: "Test scope (affected, all)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Show inputs
      shell: bash
      run: |
        echo "workdir=${{ inputs.workdir }}"
        echo "package=${{ inputs.package }}"
        echo "part=${{ inputs.part }}"
        echo "test-mode=${{ inputs.test-mode }}"
        echo "test-scope=${{ inputs.test-scope }}"

    - name: Run tests for the patched version of the package
      shell: bash
      id: run-patched
      env:
        WORKDIR: ${{ inputs.workdir }}
        PACKAGE: ${{ inputs.package }}
      run: |
        echo "::group::🧪 Running tests for package $PACKAGE"
        invenio-testrig test \
            $WORKDIR \
            $PACKAGE \
            --apply-patches \
            ${{ inputs.part && format('--part {0}', inputs.part) || '' }} \
            || true
        echo "::endgroup::"

        STATUS_FILE=$WORKDIR/artifacts/$PACKAGE/patched_status.json

        echo "test_patch_status=$(cat $STATUS_FILE | jq -r '.status')" >> $GITHUB_OUTPUT
        status=$(cat $STATUS_FILE | jq -r '.status')

        echo "Status file: $STATUS_FILE"
        cat $STATUS_FILE

        if [ "$status" == "failed" ]; then
            exit 1
        fi

    - name: Run unpatched tests for the package
      shell: bash
      id: run-unpatched
      if: always()
      env:
        WORKDIR: ${{ inputs.workdir }}
        PACKAGE: ${{ inputs.package }}
      run: |
        should_run_unpatched=false
        if [ "${{ inputs.test-mode }}" == "run-all" ]; then
            echo "Will run unpatched tests because test-mode is 'run-all'"
            should_run_unpatched=true
        fi
        if [ "${{inputs.test-mode}}" == 'stop-on-success' ] && [ "${{ steps.run-patched.outputs.test_patch_status }}" == "failed" ]; then
            echo "Will run unpatched tests because test-mode is 'stop-on-success' and the patched tests failed"
            should_run_unpatched=true
        fi
        if [ "${{ steps.run-patched.outputs.test_patch_status }}" == 'skipped' ] && [ "${{ inputs.test-scope }}" == 'all' ]; then
            echo "Will run unpatched tests because the patched tests were skipped and test-scope is 'all'"
            should_run_unpatched=true
        fi

        if [ ! "$should_run_unpatched" == "true" ]; then
            echo "Skipping unpatched tests"
            exit 0
        fi

        echo "::group::🧪 Running tests for the unpatched version of package $PACKAGE"
        invenio-testrig test \
            $WORKDIR \
            $PACKAGE \
            ${{ inputs.part && format('--part {0}', inputs.part) || '' }} \
            || true
        echo "::endgroup::"

        STATUS_FILE=$WORKDIR/artifacts/$PACKAGE/original_status.json

        echo "test_original_status=$(cat $STATUS_FILE | jq -r '.status')" >> $GITHUB_OUTPUT
        status=$(cat $STATUS_FILE | jq -r '.status')

        if [ "$status" == "failed" ] || [ "$status" == "skipped" ]; then
            exit 1
        fi

    - name: Apply part number
      if: always() && inputs.part != ''
      shell: bash
      env:
        WORKDIR: ${{ inputs.workdir }}
        PACKAGE: ${{ inputs.package }}
      run: |
        cd $WORKDIR
        mv "artifacts/$PACKAGE" "artifacts/${PACKAGE}-${{ inputs.part }}"

    - name: Store test results as artifact
      if: always() && inputs.part == ''
      uses: actions/upload-artifact@v6
      with:
        name: test-results-${{ inputs.package }}
        path: ${{ inputs.workdir }}/artifacts
        retention-days: 1

    - name: Store test results for part as artifact
      if: always() && inputs.part != ''
      uses: actions/upload-artifact@v6
      with:
        name: test-results-${{ inputs.package }}-${{ inputs.part }}
        path: ${{ inputs.workdir }}/artifacts
        retention-days: 1
